blank_issues_enabled: false
contact_links:
    - name: Questions
      url: https://github.com/SixLabors/ImageSharp/discussions/categories/q-a
      about: Ask the community for help.
    - name: Feature Request
      url: https://github.com/SixLabors/ImageSharp/discussions/categories/ideas
      about: Share ideas for new features for this project.
